-- ============================================================
-- Sports Recommendation System
-- UCS310 - Database Management System
-- Thapar Institute of Engineering and Technology
-- Submitted by: Samyak Jain (1024170400), Sangam Sangwan (1024170388)
-- Batch: 2Q34  |  Instructor: Ms. Gayatri Saxena
-- ============================================================
-- FILE: 01_schema.sql
-- PURPOSE: DDL - Create all tables with constraints
-- CHANGES:  Added CHECK constraints on all categorical VARCHAR2 columns
-- ============================================================

-- Users table: stores basic demographics
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR2(100) NOT NULL,
    age     NUMBER        NOT NULL,
    gender  VARCHAR2(20)  NOT NULL,
    CONSTRAINT chk_users_gender
        CHECK (gender IN ('Male', 'Female', 'Other')),
    CONSTRAINT chk_users_age
        CHECK (age BETWEEN 5 AND 100)
);

-- Physical traits: height, weight, stamina, flexibility per user
CREATE TABLE physical_traits (
    trait_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           NUMBER       NOT NULL,
    height_cm         NUMBER       NOT NULL,
    weight_kg         NUMBER       NOT NULL,
    stamina_level     VARCHAR2(20) NOT NULL,   -- 'Low' | 'Medium' | 'High'
    flexibility_level VARCHAR2(20) NOT NULL,   -- 'Low' | 'Medium' | 'High'
    CONSTRAINT fk_physical_traits_user
        FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT chk_stamina_level
        CHECK (stamina_level IN ('Low', 'Medium', 'High')),
    CONSTRAINT chk_flexibility_level
        CHECK (flexibility_level IN ('Low', 'Medium', 'High')),
    CONSTRAINT chk_height_cm
        CHECK (height_cm > 0),
    CONSTRAINT chk_weight_kg
        CHECK (weight_kg > 0)
);

-- Lifestyle: activity habits, available time, and health conditions
CREATE TABLE lifestyle (
    lifestyle_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         NUMBER        NOT NULL,
    activity_level  VARCHAR2(20)  NOT NULL,   -- 'Low' | 'Moderate' | 'Active'
    free_time_hours NUMBER        NOT NULL,   -- hours available per session
    health_issue    VARCHAR2(100) NOT NULL,   -- 'None' or specific condition
    CONSTRAINT fk_lifestyle_user
        FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT chk_activity_level
        CHECK (activity_level IN ('Low', 'Moderate', 'Active')),
    CONSTRAINT chk_free_time_hours
        CHECK (free_time_hours >= 0)
);

-- Interests: indoor/outdoor, team/solo, competitiveness preference
CREATE TABLE interests (
    interest_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         NUMBER       NOT NULL,
    prefers_indoor  VARCHAR2(5)  NOT NULL,   -- 'Yes' | 'No'
    prefers_team    VARCHAR2(5)  NOT NULL,   -- 'Yes' | 'No'
    competitiveness VARCHAR2(20) NOT NULL,   -- 'Low' | 'Medium' | 'High'
    CONSTRAINT fk_interests_user
        FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT chk_prefers_indoor
        CHECK (prefers_indoor IN ('Yes', 'No')),
    CONSTRAINT chk_prefers_team
        CHECK (prefers_team IN ('Yes', 'No')),
    CONSTRAINT chk_competitiveness
        CHECK (competitiveness IN ('Low', 'Medium', 'High'))
);

-- Sports catalogue: eligibility criteria and requirements per sport
CREATE TABLE sports (
    sport_id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_name            VARCHAR2(100) NOT NULL,
    sport_type            VARCHAR2(30)  NOT NULL,   -- 'Indoor' | 'Outdoor'
    required_stamina      VARCHAR2(20)  NOT NULL,   -- 'Low' | 'Medium' | 'High'
    is_team_sport         VARCHAR2(5)   NOT NULL,   -- 'Yes' | 'No'
    min_weight_kg         NUMBER        NOT NULL,
    max_kg_weight         NUMBER        NOT NULL,
    min_time_required_hrs NUMBER        NOT NULL,   -- minimum hours per session
    low_impact            VARCHAR2(5)   NOT NULL,   -- 'Yes' | 'No'
    min_age               NUMBER        NOT NULL,
    max_age               NUMBER        NOT NULL,
    equipment_required    VARCHAR2(100) NOT NULL,
    CONSTRAINT chk_sport_type
        CHECK (sport_type IN ('Indoor', 'Outdoor')),
    CONSTRAINT chk_required_stamina
        CHECK (required_stamina IN ('Low', 'Medium', 'High')),
    CONSTRAINT chk_is_team_sport
        CHECK (is_team_sport IN ('Yes', 'No')),
    CONSTRAINT chk_low_impact
        CHECK (low_impact IN ('Yes', 'No')),
    CONSTRAINT chk_weight_range
        CHECK (min_weight_kg < max_kg_weight),
    CONSTRAINT chk_age_range
        CHECK (min_age < max_age),
    CONSTRAINT chk_min_time
        CHECK (min_time_required_hrs > 0)
);
