-- ============================================================
-- Sports Recommendation System — COMBINED SCRIPT
-- UCS310 - Database Management System
-- Thapar Institute of Engineering and Technology
-- Submitted by: Samyak Jain (1024170400), Sangam Sangwan (1024170388)
-- Batch: 2Q34  |  Instructor: Ms. Gayatri Saxena
--
-- HOW TO RUN ON Oracle LiveSQL (livesql.oracle.com):
--   1. Sign in with a free Oracle account
--   2. Open "SQL Worksheet"
--   3. Paste this entire script
--   4. Click "Run Script" (F5 / the play-all button)
--
-- EXECUTION ORDER (already correct in this file):
--   STEP 1 — Function       (needed by the VIEW)
--   STEP 2 — Tables         (DDL)
--   STEP 3 — Trigger        (fires on INSERT/UPDATE to users)
--   STEP 4 — Data           (DML)
--   STEP 5 — View           (depends on function + tables)
--   STEP 6 — Procedures     (depend on view)
--   STEP 7 — Analytical SQL (SELECT queries)
--   STEP 8 — Demo calls     (EXEC + verification SELECTs)
-- ============================================================


-- ════════════════════════════════════════════════════════════
-- STEP 1: FUNCTION — get_stamina_score
-- Must be created BEFORE the view that references it.
-- ════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION get_stamina_score (
    p_level IN VARCHAR2
) RETURN NUMBER
IS
BEGIN
    RETURN CASE UPPER(p_level)
               WHEN 'LOW'    THEN 1
               WHEN 'MEDIUM' THEN 2
               WHEN 'HIGH'   THEN 3
               ELSE 0
           END;
END get_stamina_score;
/


-- ════════════════════════════════════════════════════════════
-- STEP 2: DDL — Create all tables
-- ════════════════════════════════════════════════════════════

-- Clean slate: drop tables if they already exist (ignore errors if not present)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE interests        CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE lifestyle        CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE physical_traits  CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE sports           CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE users            CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Users table
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR2(100) NOT NULL,
    age     NUMBER        NOT NULL,
    gender  VARCHAR2(20)  NOT NULL,
    CONSTRAINT chk_users_gender CHECK (gender IN ('Male', 'Female', 'Other')),
    CONSTRAINT chk_users_age    CHECK (age BETWEEN 5 AND 100)
);

-- Physical traits
CREATE TABLE physical_traits (
    trait_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           NUMBER       NOT NULL,
    height_cm         NUMBER       NOT NULL,
    weight_kg         NUMBER       NOT NULL,
    stamina_level     VARCHAR2(20) NOT NULL,
    flexibility_level VARCHAR2(20) NOT NULL,
    CONSTRAINT fk_physical_traits_user  FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT chk_stamina_level        CHECK (stamina_level     IN ('Low', 'Medium', 'High')),
    CONSTRAINT chk_flexibility_level    CHECK (flexibility_level IN ('Low', 'Medium', 'High')),
    CONSTRAINT chk_height_cm            CHECK (height_cm > 0),
    CONSTRAINT chk_weight_kg            CHECK (weight_kg > 0)
);

-- Lifestyle
CREATE TABLE lifestyle (
    lifestyle_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         NUMBER        NOT NULL,
    activity_level  VARCHAR2(20)  NOT NULL,
    free_time_hours NUMBER        NOT NULL,
    health_issue    VARCHAR2(100) NOT NULL,
    CONSTRAINT fk_lifestyle_user   FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT chk_activity_level  CHECK (activity_level IN ('Low', 'Moderate', 'Active')),
    CONSTRAINT chk_free_time_hours CHECK (free_time_hours >= 0)
);

-- Interests
CREATE TABLE interests (
    interest_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         NUMBER       NOT NULL,
    prefers_indoor  VARCHAR2(5)  NOT NULL,
    prefers_team    VARCHAR2(5)  NOT NULL,
    competitiveness VARCHAR2(20) NOT NULL,
    CONSTRAINT fk_interests_user    FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT chk_prefers_indoor   CHECK (prefers_indoor   IN ('Yes', 'No')),
    CONSTRAINT chk_prefers_team     CHECK (prefers_team     IN ('Yes', 'No')),
    CONSTRAINT chk_competitiveness  CHECK (competitiveness  IN ('Low', 'Medium', 'High'))
);

-- Sports catalogue
CREATE TABLE sports (
    sport_id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_name            VARCHAR2(100) NOT NULL,
    sport_type            VARCHAR2(30)  NOT NULL,
    required_stamina      VARCHAR2(20)  NOT NULL,
    is_team_sport         VARCHAR2(5)   NOT NULL,
    min_weight_kg         NUMBER        NOT NULL,
    max_kg_weight         NUMBER        NOT NULL,
    min_time_required_hrs NUMBER        NOT NULL,
    low_impact            VARCHAR2(5)   NOT NULL,
    min_age               NUMBER        NOT NULL,
    max_age               NUMBER        NOT NULL,
    equipment_required    VARCHAR2(100) NOT NULL,
    CONSTRAINT chk_sport_type       CHECK (sport_type      IN ('Indoor', 'Outdoor')),
    CONSTRAINT chk_required_stamina CHECK (required_stamina IN ('Low', 'Medium', 'High')),
    CONSTRAINT chk_is_team_sport    CHECK (is_team_sport   IN ('Yes', 'No')),
    CONSTRAINT chk_low_impact       CHECK (low_impact      IN ('Yes', 'No')),
    CONSTRAINT chk_weight_range     CHECK (min_weight_kg < max_kg_weight),
    CONSTRAINT chk_age_range        CHECK (min_age < max_age),
    CONSTRAINT chk_min_time         CHECK (min_time_required_hrs > 0)
);


-- ════════════════════════════════════════════════════════════
-- STEP 3: TRIGGER — validate user age with a friendly message
-- ════════════════════════════════════════════════════════════

CREATE OR REPLACE TRIGGER trg_validate_user_age
BEFORE INSERT OR UPDATE ON users
FOR EACH ROW
BEGIN
    IF :NEW.age < 5 OR :NEW.age > 100 THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'Invalid age ' || :NEW.age ||
            ' for user "' || :NEW.name ||
            '". Age must be between 5 and 100.'
        );
    END IF;
END;
/


-- ════════════════════════════════════════════════════════════
-- STEP 4: DML — Insert sample data (40 users, 8 sports)
-- ════════════════════════════════════════════════════════════

-- ─── USERS (40 total) ─────────────────────────────────────
INSERT INTO users (user_id, name, age, gender) VALUES (1,  'Aarav Sharma',    19, 'Male');
INSERT INTO users (user_id, name, age, gender) VALUES (2,  'Diya Verma',      20, 'Female');
INSERT INTO users (user_id, name, age, gender) VALUES (3,  'Kabir Mehta',     21, 'Male');
INSERT INTO users (user_id, name, age, gender) VALUES (4,  'Ananya Gupta',    18, 'Female');
INSERT INTO users (user_id, name, age, gender) VALUES (5,  'Rohan Singh',     22, 'Male');
-- User 6: deliberately unmatchable — only 0.5 free hours (below all sports'
-- min_time_required_hrs of 1), so no sport can be recommended. This confirms
-- the stored procedure's "No sports matched" fallback branch executes correctly.
INSERT INTO users (user_id, name, age, gender) VALUES (6,  'Priya Nair',      17, 'Female');
INSERT INTO users (user_id, name, age, gender) VALUES (7,  'Arjun Patel',     23, 'Male');
INSERT INTO users (user_id, name, age, gender) VALUES (8,  'Sneha Reddy',     21, 'Female');
INSERT INTO users (user_id, name, age, gender) VALUES (9,  'Vikram Joshi',    24, 'Male');
INSERT INTO users (user_id, name, age, gender) VALUES (10, 'Meera Iyer',      20, 'Female');
INSERT INTO users (user_id, name, age, gender) VALUES (11, 'Rahul Kapoor',    22, 'Male');
INSERT INTO users (user_id, name, age, gender) VALUES (12, 'Pooja Sharma',    19, 'Female');
INSERT INTO users (user_id, name, age, gender) VALUES (13, 'Karan Malhotra',  25, 'Male');
INSERT INTO users (user_id, name, age, gender) VALUES (14, 'Neha Agarwal',    18, 'Female');
INSERT INTO users (user_id, name, age, gender) VALUES (15, 'Aditya Verma',    21, 'Male');
INSERT INTO users (user_id, name, age, gender) VALUES (16, 'Ishita Singh',    23, 'Female');
INSERT INTO users (user_id, name, age, gender) VALUES (17, 'Aman Gupta',      18, 'Male');
INSERT INTO users (user_id, name, age, gender) VALUES (18, 'Riya Mehta',      19, 'Female');
INSERT INTO users (user_id, name, age, gender) VALUES (19, 'Sahil Khan',      20, 'Male');
INSERT INTO users (user_id, name, age, gender) VALUES (20, 'Anjali Desai',    21, 'Female');
INSERT INTO users (user_id, name, age, gender) VALUES (21, 'Nikhil Jain',     22, 'Male');
INSERT INTO users (user_id, name, age, gender) VALUES (22, 'Kavya Nair',      23, 'Female');
INSERT INTO users (user_id, name, age, gender) VALUES (23, 'Rohit Yadav',     24, 'Male');
INSERT INTO users (user_id, name, age, gender) VALUES (24, 'Simran Kaur',     20, 'Female');
INSERT INTO users (user_id, name, age, gender) VALUES (25, 'Deepak Sharma',   21, 'Male');
INSERT INTO users (user_id, name, age, gender) VALUES (26, 'Priyanka Das',    22, 'Female');
INSERT INTO users (user_id, name, age, gender) VALUES (27, 'Varun Bansal',    23, 'Male');
INSERT INTO users (user_id, name, age, gender) VALUES (28, 'Nisha Verma',     19, 'Female');
INSERT INTO users (user_id, name, age, gender) VALUES (29, 'Akash Singh',     20, 'Male');
INSERT INTO users (user_id, name, age, gender) VALUES (30, 'Pallavi Gupta',   21, 'Female');
INSERT INTO users (user_id, name, age, gender) VALUES (31, 'Tarun Arora',     22, 'Male');
INSERT INTO users (user_id, name, age, gender) VALUES (32, 'Shreya Kapoor',   23, 'Female');
INSERT INTO users (user_id, name, age, gender) VALUES (33, 'Mohit Saini',     24, 'Male');
INSERT INTO users (user_id, name, age, gender) VALUES (34, 'Aditi Mishra',    18, 'Female');
INSERT INTO users (user_id, name, age, gender) VALUES (35, 'Yash Thakur',     21, 'Male');
INSERT INTO users (user_id, name, age, gender) VALUES (36, 'Tanvi Joshi',     22, 'Female');
INSERT INTO users (user_id, name, age, gender) VALUES (37, 'Harsh Vardhan',   23, 'Male');
INSERT INTO users (user_id, name, age, gender) VALUES (38, 'Isha Arora',      20, 'Female');
INSERT INTO users (user_id, name, age, gender) VALUES (39, 'Manish Pandey',   21, 'Male');
INSERT INTO users (user_id, name, age, gender) VALUES (40, 'Ritika Singh',    22, 'Female');


-- ─── PHYSICAL TRAITS (all 40 users) ─────────────────────────
-- Columns: trait_id, user_id, height_cm, weight_kg, stamina_level, flexibility_level
INSERT INTO physical_traits VALUES (1,  1,  175, 68, 'High',   'Medium');
INSERT INTO physical_traits VALUES (2,  2,  162, 54, 'Medium', 'High');
INSERT INTO physical_traits VALUES (3,  3,  180, 82, 'High',   'Low');
INSERT INTO physical_traits VALUES (4,  4,  158, 50, 'Low',    'High');
INSERT INTO physical_traits VALUES (5,  5,  172, 74, 'Medium', 'Medium');
INSERT INTO physical_traits VALUES (6,  6,  160, 52, 'Medium', 'Medium');
INSERT INTO physical_traits VALUES (7,  7,  178, 76, 'High',   'Low');
INSERT INTO physical_traits VALUES (8,  8,  163, 56, 'Medium', 'High');
INSERT INTO physical_traits VALUES (9,  9,  182, 85, 'High',   'Medium');
INSERT INTO physical_traits VALUES (10, 10, 155, 48, 'Low',    'High');
INSERT INTO physical_traits VALUES (11, 11, 170, 72, 'High',   'Medium');
INSERT INTO physical_traits VALUES (12, 12, 161, 53, 'Low',    'High');
INSERT INTO physical_traits VALUES (13, 13, 176, 78, 'Medium', 'Low');
INSERT INTO physical_traits VALUES (14, 14, 157, 49, 'Low',    'High');
INSERT INTO physical_traits VALUES (15, 15, 174, 70, 'High',   'Medium');
INSERT INTO physical_traits VALUES (16, 16, 165, 58, 'Medium', 'High');
INSERT INTO physical_traits VALUES (17, 17, 168, 65, 'High',   'Low');
INSERT INTO physical_traits VALUES (18, 18, 159, 51, 'Low',    'High');
INSERT INTO physical_traits VALUES (19, 19, 173, 69, 'Medium', 'Medium');
INSERT INTO physical_traits VALUES (20, 20, 164, 57, 'Medium', 'High');
INSERT INTO physical_traits VALUES (21, 21, 177, 80, 'High',   'Low');
INSERT INTO physical_traits VALUES (22, 22, 162, 55, 'Medium', 'High');
INSERT INTO physical_traits VALUES (23, 23, 183, 88, 'High',   'Medium');
INSERT INTO physical_traits VALUES (24, 24, 158, 50, 'Low',    'High');
INSERT INTO physical_traits VALUES (25, 25, 171, 73, 'High',   'Medium');
INSERT INTO physical_traits VALUES (26, 26, 166, 60, 'Medium', 'High');
INSERT INTO physical_traits VALUES (27, 27, 179, 83, 'High',   'Low');
INSERT INTO physical_traits VALUES (28, 28, 160, 52, 'Low',    'High');
INSERT INTO physical_traits VALUES (29, 29, 174, 71, 'Medium', 'Medium');
INSERT INTO physical_traits VALUES (30, 30, 163, 56, 'Low',    'High');
INSERT INTO physical_traits VALUES (31, 31, 176, 75, 'High',   'Medium');
INSERT INTO physical_traits VALUES (32, 32, 167, 61, 'Medium', 'High');
INSERT INTO physical_traits VALUES (33, 33, 181, 86, 'High',   'Low');
INSERT INTO physical_traits VALUES (34, 34, 156, 48, 'Low',    'High');
INSERT INTO physical_traits VALUES (35, 35, 172, 70, 'High',   'Medium');
INSERT INTO physical_traits VALUES (36, 36, 164, 57, 'Medium', 'High');
INSERT INTO physical_traits VALUES (37, 37, 178, 79, 'High',   'Medium');
INSERT INTO physical_traits VALUES (38, 38, 161, 54, 'Low',    'High');
INSERT INTO physical_traits VALUES (39, 39, 175, 72, 'Medium', 'Medium');
INSERT INTO physical_traits VALUES (40, 40, 165, 59, 'Medium', 'High');


-- ─── LIFESTYLE (all 40 users) ────────────────────────────────
-- Columns: lifestyle_id, user_id, activity_level, free_time_hours, health_issue
-- Health issues deliberately varied: None, Asthma, Knee Pain, Back Pain, Diabetes
INSERT INTO lifestyle VALUES (1,  1,  'Active',   2,   'None');
INSERT INTO lifestyle VALUES (2,  2,  'Moderate', 1,   'None');
INSERT INTO lifestyle VALUES (3,  3,  'Active',   3,   'Knee Pain');
INSERT INTO lifestyle VALUES (4,  4,  'Low',      1,   'Asthma');
INSERT INTO lifestyle VALUES (5,  5,  'Moderate', 2,   'None');
INSERT INTO lifestyle VALUES (6,  6,  'Low',      0.5, 'None');
INSERT INTO lifestyle VALUES (7,  7,  'Active',   3,   'None');
INSERT INTO lifestyle VALUES (8,  8,  'Moderate', 2,   'None');
INSERT INTO lifestyle VALUES (9,  9,  'Active',   2,   'Back Pain');
INSERT INTO lifestyle VALUES (10, 10, 'Low',      1,   'Asthma');
INSERT INTO lifestyle VALUES (11, 11, 'Active',   3,   'None');
INSERT INTO lifestyle VALUES (12, 12, 'Low',      1,   'None');
INSERT INTO lifestyle VALUES (13, 13, 'Moderate', 2,   'Knee Pain');
INSERT INTO lifestyle VALUES (14, 14, 'Low',      1,   'Asthma');
INSERT INTO lifestyle VALUES (15, 15, 'Active',   2,   'None');
INSERT INTO lifestyle VALUES (16, 16, 'Moderate', 2,   'None');
INSERT INTO lifestyle VALUES (17, 17, 'Active',   3,   'None');
INSERT INTO lifestyle VALUES (18, 18, 'Low',      1,   'None');
INSERT INTO lifestyle VALUES (19, 19, 'Moderate', 2,   'Diabetes');
INSERT INTO lifestyle VALUES (20, 20, 'Moderate', 1,   'None');
INSERT INTO lifestyle VALUES (21, 21, 'Active',   3,   'None');
INSERT INTO lifestyle VALUES (22, 22, 'Moderate', 2,   'None');
INSERT INTO lifestyle VALUES (23, 23, 'Active',   2,   'None');
INSERT INTO lifestyle VALUES (24, 24, 'Low',      1,   'Asthma');
INSERT INTO lifestyle VALUES (25, 25, 'Active',   3,   'None');
INSERT INTO lifestyle VALUES (26, 26, 'Moderate', 2,   'None');
INSERT INTO lifestyle VALUES (27, 27, 'Active',   2,   'Back Pain');
INSERT INTO lifestyle VALUES (28, 28, 'Low',      1,   'None');
INSERT INTO lifestyle VALUES (29, 29, 'Moderate', 2,   'None');
INSERT INTO lifestyle VALUES (30, 30, 'Low',      1,   'Asthma');
INSERT INTO lifestyle VALUES (31, 31, 'Active',   3,   'None');
INSERT INTO lifestyle VALUES (32, 32, 'Moderate', 2,   'None');
INSERT INTO lifestyle VALUES (33, 33, 'Active',   2,   'Knee Pain');
INSERT INTO lifestyle VALUES (34, 34, 'Low',      1,   'None');
INSERT INTO lifestyle VALUES (35, 35, 'Active',   3,   'None');
INSERT INTO lifestyle VALUES (36, 36, 'Moderate', 2,   'None');
INSERT INTO lifestyle VALUES (37, 37, 'Active',   2,   'None');
INSERT INTO lifestyle VALUES (38, 38, 'Low',      1,   'None');
INSERT INTO lifestyle VALUES (39, 39, 'Moderate', 2,   'Diabetes');
INSERT INTO lifestyle VALUES (40, 40, 'Moderate', 1,   'None');


-- ─── INTERESTS (all 40 users) ────────────────────────────────
-- Columns: interest_id, user_id, prefers_indoor, prefers_team, competitiveness
-- Mix of indoor/outdoor and team/solo preferences spread across all users
INSERT INTO interests VALUES (1,  1,  'No',  'Yes', 'High');
INSERT INTO interests VALUES (2,  2,  'Yes', 'No',  'Medium');
INSERT INTO interests VALUES (3,  3,  'No',  'Yes', 'High');
INSERT INTO interests VALUES (4,  4,  'Yes', 'No',  'Low');
INSERT INTO interests VALUES (5,  5,  'No',  'No',  'Medium');
INSERT INTO interests VALUES (6,  6,  'Yes', 'No',  'Low');
INSERT INTO interests VALUES (7,  7,  'No',  'Yes', 'High');
INSERT INTO interests VALUES (8,  8,  'Yes', 'No',  'Medium');
INSERT INTO interests VALUES (9,  9,  'No',  'No',  'Medium');
INSERT INTO interests VALUES (10, 10, 'Yes', 'No',  'Low');
INSERT INTO interests VALUES (11, 11, 'No',  'Yes', 'High');
INSERT INTO interests VALUES (12, 12, 'Yes', 'No',  'Low');
INSERT INTO interests VALUES (13, 13, 'No',  'No',  'Medium');
INSERT INTO interests VALUES (14, 14, 'Yes', 'No',  'Low');
INSERT INTO interests VALUES (15, 15, 'No',  'Yes', 'High');
INSERT INTO interests VALUES (16, 16, 'Yes', 'No',  'Medium');
INSERT INTO interests VALUES (17, 17, 'Yes', 'Yes', 'High');
INSERT INTO interests VALUES (18, 18, 'Yes', 'No',  'Low');
INSERT INTO interests VALUES (19, 19, 'No',  'No',  'Medium');
INSERT INTO interests VALUES (20, 20, 'Yes', 'No',  'Medium');
INSERT INTO interests VALUES (21, 21, 'No',  'Yes', 'High');
INSERT INTO interests VALUES (22, 22, 'Yes', 'No',  'Medium');
INSERT INTO interests VALUES (23, 23, 'No',  'No',  'High');
INSERT INTO interests VALUES (24, 24, 'Yes', 'No',  'Low');
INSERT INTO interests VALUES (25, 25, 'No',  'Yes', 'High');
INSERT INTO interests VALUES (26, 26, 'Yes', 'No',  'Medium');
INSERT INTO interests VALUES (27, 27, 'No',  'No',  'Medium');
INSERT INTO interests VALUES (28, 28, 'Yes', 'No',  'Low');
INSERT INTO interests VALUES (29, 29, 'No',  'No',  'Medium');
INSERT INTO interests VALUES (30, 30, 'Yes', 'No',  'Low');
INSERT INTO interests VALUES (31, 31, 'No',  'Yes', 'High');
INSERT INTO interests VALUES (32, 32, 'Yes', 'No',  'Medium');
INSERT INTO interests VALUES (33, 33, 'No',  'No',  'Medium');
INSERT INTO interests VALUES (34, 34, 'Yes', 'No',  'Low');
INSERT INTO interests VALUES (35, 35, 'No',  'Yes', 'High');
INSERT INTO interests VALUES (36, 36, 'Yes', 'No',  'Medium');
INSERT INTO interests VALUES (37, 37, 'No',  'No',  'High');
INSERT INTO interests VALUES (38, 38, 'Yes', 'No',  'Low');
INSERT INTO interests VALUES (39, 39, 'No',  'No',  'Medium');
INSERT INTO interests VALUES (40, 40, 'Yes', 'No',  'Medium');


-- ─── SPORTS CATALOGUE (8 sports, unchanged) ─────────────────
INSERT INTO sports (sport_id, sport_name, sport_type, required_stamina, is_team_sport, min_weight_kg, max_kg_weight, min_time_required_hrs, low_impact, min_age, max_age, equipment_required)
VALUES (1, 'Football',     'Outdoor', 'High',   'Yes', 50, 90,  2, 'No',  15, 30, 'Football Kit');
INSERT INTO sports (sport_id, sport_name, sport_type, required_stamina, is_team_sport, min_weight_kg, max_kg_weight, min_time_required_hrs, low_impact, min_age, max_age, equipment_required)
VALUES (2, 'Badminton',    'Indoor',  'Medium', 'No',  40, 85,  1, 'Yes', 12, 40, 'Racket');
INSERT INTO sports (sport_id, sport_name, sport_type, required_stamina, is_team_sport, min_weight_kg, max_kg_weight, min_time_required_hrs, low_impact, min_age, max_age, equipment_required)
VALUES (3, 'Basketball',   'Indoor',  'High',   'Yes', 50, 95,  2, 'No',  15, 28, 'Basketball Shoes');
INSERT INTO sports (sport_id, sport_name, sport_type, required_stamina, is_team_sport, min_weight_kg, max_kg_weight, min_time_required_hrs, low_impact, min_age, max_age, equipment_required)
VALUES (4, 'Swimming',     'Indoor',  'Medium', 'No',  35, 100, 1, 'Yes', 10, 45, 'Swimwear');
INSERT INTO sports (sport_id, sport_name, sport_type, required_stamina, is_team_sport, min_weight_kg, max_kg_weight, min_time_required_hrs, low_impact, min_age, max_age, equipment_required)
VALUES (5, 'Yoga',         'Indoor',  'Low',    'No',  35, 110, 1, 'Yes', 12, 60, 'Yoga Mat');
INSERT INTO sports (sport_id, sport_name, sport_type, required_stamina, is_team_sport, min_weight_kg, max_kg_weight, min_time_required_hrs, low_impact, min_age, max_age, equipment_required)
VALUES (6, 'Table Tennis', 'Indoor',  'Low',    'No',  35, 90,  1, 'Yes', 12, 50, 'Table Tennis Paddle');
INSERT INTO sports (sport_id, sport_name, sport_type, required_stamina, is_team_sport, min_weight_kg, max_kg_weight, min_time_required_hrs, low_impact, min_age, max_age, equipment_required)
VALUES (7, 'Volleyball',   'Outdoor', 'Medium', 'Yes', 45, 90,  2, 'No',  15, 30, 'Volleyball');
INSERT INTO sports (sport_id, sport_name, sport_type, required_stamina, is_team_sport, min_weight_kg, max_kg_weight, min_time_required_hrs, low_impact, min_age, max_age, equipment_required)
VALUES (8, 'Cycling',      'Outdoor', 'Medium', 'No',  40, 95,  1, 'Yes', 14, 45, 'Bicycle');

COMMIT;


-- ════════════════════════════════════════════════════════════
-- STEP 5: VIEW — sport_recommendation_view
-- Encapsulates all 7 matching criteria in one place.
-- ════════════════════════════════════════════════════════════

CREATE OR REPLACE VIEW sport_recommendation_view AS
SELECT
    u.user_id,
    u.name,
    s.sport_id,
    s.sport_name,
    s.sport_type,
    s.equipment_required
FROM users u
JOIN physical_traits pt ON pt.user_id = u.user_id
JOIN lifestyle        l  ON l.user_id  = u.user_id
JOIN interests        i  ON i.user_id  = u.user_id
JOIN sports           s
    ON  pt.weight_kg       BETWEEN s.min_weight_kg AND s.max_kg_weight
    AND u.age              BETWEEN s.min_age        AND s.max_age
    AND l.free_time_hours  >= s.min_time_required_hrs
    -- Stamina: user must meet or exceed sport requirement
    AND get_stamina_score(pt.stamina_level) >= get_stamina_score(s.required_stamina)
    -- Team preference must match exactly
    AND i.prefers_team = s.is_team_sport
    -- Indoor/outdoor preference must match sport type
    AND (
        (i.prefers_indoor = 'Yes' AND s.sport_type = 'Indoor')
     OR (i.prefers_indoor = 'No'  AND s.sport_type = 'Outdoor')
    )
    -- Health issue → low-impact sports only
    AND (l.health_issue = 'None' OR s.low_impact = 'Yes');


-- ════════════════════════════════════════════════════════════
-- STEP 6A: PROCEDURE (implicit cursor) — recommend_sports_for_user
-- ════════════════════════════════════════════════════════════

CREATE OR REPLACE PROCEDURE recommend_sports_for_user (
    p_user_id IN NUMBER
) AS
    v_found NUMBER := 0;
BEGIN
    FOR rec IN (
        SELECT sport_name, sport_type, equipment_required
        FROM   sport_recommendation_view
        WHERE  user_id = p_user_id
        ORDER BY sport_name
    ) LOOP
        v_found := 1;
        DBMS_OUTPUT.PUT_LINE(
            'Recommended Sport: ' || rec.sport_name    ||
            ', Type: '            || rec.sport_type    ||
            ', Equipment: '       || rec.equipment_required
        );
    END LOOP;

    IF v_found = 0 THEN
        DBMS_OUTPUT.PUT_LINE('No sports matched for user ID ' || p_user_id);
    END IF;
END;
/


-- ════════════════════════════════════════════════════════════
-- STEP 6B: PROCEDURE (explicit cursor + exception handling)
--          recommend_sports_explicit
-- ════════════════════════════════════════════════════════════

CREATE OR REPLACE PROCEDURE recommend_sports_explicit (
    p_user_id IN NUMBER
) AS
    CURSOR c_sports IS
        SELECT sport_name, sport_type, equipment_required
        FROM   sport_recommendation_view
        WHERE  user_id = p_user_id
        ORDER BY sport_name;

    v_rec   c_sports%ROWTYPE;
    v_found BOOLEAN := FALSE;
    v_name  users.name%TYPE;

BEGIN
    SELECT name INTO v_name FROM users WHERE user_id = p_user_id;

    DBMS_OUTPUT.PUT_LINE('=== Recommendations for: ' || v_name || ' (ID ' || p_user_id || ') ===');

    OPEN c_sports;
    LOOP
        FETCH c_sports INTO v_rec;
        EXIT WHEN c_sports%NOTFOUND;
        v_found := TRUE;
        DBMS_OUTPUT.PUT_LINE(
            '  ► ' || v_rec.sport_name ||
            ' ['   || v_rec.sport_type || ']' ||
            ' | Equipment: ' || v_rec.equipment_required
        );
    END LOOP;
    CLOSE c_sports;

    IF NOT v_found THEN
        DBMS_OUTPUT.PUT_LINE('  No sports matched for this user profile.');
    END IF;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('ERROR: No user found with ID ' || p_user_id);
    WHEN OTHERS THEN
        IF c_sports%ISOPEN THEN CLOSE c_sports; END IF;
        DBMS_OUTPUT.PUT_LINE('Unexpected error: ' || SQLERRM);
        RAISE;
END recommend_sports_explicit;
/


-- ════════════════════════════════════════════════════════════
-- STEP 7: ANALYTICAL SQL QUERIES
-- ════════════════════════════════════════════════════════════

-- Query 1: Matched sport count per user
SELECT
    u.user_id,
    u.name,
    COUNT(s.sport_id) AS matched_sport_count
FROM users u
LEFT JOIN sport_recommendation_view s ON s.user_id = u.user_id
GROUP BY u.user_id, u.name
ORDER BY matched_sport_count DESC;

-- Query 2: Sports matched by more than 1 user (GROUP BY + HAVING)
SELECT
    s.sport_name,
    s.sport_type,
    COUNT(r.user_id) AS eligible_user_count
FROM sports s
LEFT JOIN sport_recommendation_view r ON r.sport_id = s.sport_id
GROUP BY s.sport_name, s.sport_type
HAVING COUNT(r.user_id) > 1
ORDER BY eligible_user_count DESC;

-- Query 3: Users eligible for more sports than average (subquery)
SELECT
    u.user_id,
    u.name,
    COUNT(r.sport_id) AS sport_count
FROM users u
JOIN sport_recommendation_view r ON r.user_id = u.user_id
GROUP BY u.user_id, u.name
HAVING COUNT(r.sport_id) > (
    SELECT AVG(cnt) FROM (
        SELECT COUNT(sport_id) AS cnt
        FROM   sport_recommendation_view
        GROUP BY user_id
    )
)
ORDER BY sport_count DESC;

-- Query 4: Average weight & age of eligible users per sport
SELECT
    r.sport_name,
    ROUND(AVG(pt.weight_kg), 1) AS avg_user_weight_kg,
    ROUND(AVG(u.age), 1)        AS avg_user_age,
    COUNT(r.user_id)            AS eligible_users
FROM sport_recommendation_view r
JOIN physical_traits pt ON pt.user_id = r.user_id
JOIN users u             ON u.user_id  = r.user_id
GROUP BY r.sport_name
ORDER BY eligible_users DESC;

-- Query 5: Users with health issues and their matched sports
SELECT
    u.name,
    l.health_issue,
    r.sport_name,
    r.sport_type
FROM users u
JOIN lifestyle l                ON l.user_id = u.user_id
JOIN sport_recommendation_view r ON r.user_id = u.user_id
WHERE l.health_issue <> 'None'
ORDER BY u.name, r.sport_name;


-- ════════════════════════════════════════════════════════════
-- STEP 7 (DML): UPDATE + SAVEPOINT/ROLLBACK demos
-- ════════════════════════════════════════════════════════════

-- Update Rohan Singh's free time to 3 hours
UPDATE lifestyle
SET    free_time_hours = 3
WHERE  user_id = (SELECT user_id FROM users WHERE name = 'Rohan Singh');

COMMIT;

-- SAVEPOINT + ROLLBACK demo
SAVEPOINT before_test_insert;

INSERT INTO users (user_id, name, age, gender) VALUES (99, 'Test User', 25, 'Male');

-- Verify row visible in current transaction
SELECT name FROM users WHERE user_id = 99;

-- Discard the test insert
ROLLBACK TO SAVEPOINT before_test_insert;


-- ════════════════════════════════════════════════════════════
-- STEP 8: DEMO — run recommendations for a representative sample
-- LiveSQL note: DBMS_OUTPUT appears in the "Script Output" tab.
-- ════════════════════════════════════════════════════════════

SET SERVEROUTPUT ON;

EXEC recommend_sports_explicit(1);   -- Aarav Sharma   → Football, Volleyball (Outdoor, Team, High stamina)
EXEC recommend_sports_explicit(2);   -- Diya Verma     → Badminton, Swimming, Table Tennis (Indoor, Solo)
EXEC recommend_sports_explicit(3);   -- Kabir Mehta    → No match (Knee Pain + Outdoor + Team)
EXEC recommend_sports_explicit(4);   -- Ananya Gupta   → Swimming, Table Tennis, Yoga (Indoor, Solo, Asthma)
EXEC recommend_sports_explicit(5);   -- Rohan Singh    → Cycling (Outdoor, Solo, Medium stamina)
EXEC recommend_sports_explicit(6);   -- Priya Nair     → No match (free_time = 0.5 hrs)
EXEC recommend_sports_explicit(7);   -- Arjun Patel    → Football, Volleyball (Outdoor, Team, High stamina)
EXEC recommend_sports_explicit(8);   -- Sneha Reddy    → Badminton, Swimming, Table Tennis (Indoor, Solo)
EXEC recommend_sports_explicit(11);  -- Rahul Kapoor   → Football, Volleyball (Outdoor, Team, High stamina)
EXEC recommend_sports_explicit(15);  -- Aditya Verma   → Football, Volleyball (Outdoor, Team, High stamina)
EXEC recommend_sports_explicit(17);  -- Aman Gupta     → Basketball (Indoor, Team, High stamina)
EXEC recommend_sports_explicit(21);  -- Nikhil Jain    → Football, Volleyball (Outdoor, Team, High stamina)
EXEC recommend_sports_explicit(25);  -- Deepak Sharma  → Football, Volleyball (Outdoor, Team, High stamina)
EXEC recommend_sports_explicit(40);  -- Ritika Singh   → Badminton, Swimming, Table Tennis, Yoga

-- Full view output for reference
SELECT * FROM sport_recommendation_view ORDER BY user_id, sport_name;

-- ── EXPECTED OUTPUT (key users) ──────────────────────────────
-- User  1 (Aarav):   Football, Volleyball
-- User  2 (Diya):    Badminton, Swimming, Table Tennis
-- User  3 (Kabir):   No sports matched  (Knee Pain, Outdoor-only)
-- User  4 (Ananya):  Swimming, Table Tennis, Yoga  (Asthma → low-impact only)
-- User  5 (Rohan):   Cycling
-- User  6 (Priya):   No sports matched  (free_time < 1 hr)
-- User  7 (Arjun):   Football, Volleyball
-- User  8 (Sneha):   Badminton, Swimming, Table Tennis
-- User 17 (Aman):    Basketball  (Indoor + Team + High stamina)
-- User 40 (Ritika):  Badminton, Swimming, Table Tennis, Yoga
